# Generated by Django 5.0.1 on 2024-01-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='a_pets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.pets'),
        ),
    ]
