# Generated by Django 5.0.2 on 2024-03-17 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_subscription1_subscription2_subscription3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_subscription_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_date', models.DateField(auto_now_add=True)),
                ('a_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.subscription1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
