# Generated by Django 5.0.2 on 2024-04-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_basic_subscription_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription1',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
