# Generated by Django 5.0.2 on 2024-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_alter_subscription1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription2',
            name='subscription',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription3',
            name='subscription',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Premium', max_length=20),
        ),
    ]
