# Generated by Django 4.2.8 on 2024-01-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='user',
        ),
    ]
